#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    remote_path="$3"@"$2":~
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$remote_path"
fi
