#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

total_args=$#

if [ "$total_args" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path="$1"
	server_ip="$2"
	username="$3"
	path_ssh="$4"

	scp -o StrictHostKeyChecking=no -i "$path_ssh" "$file_path" "$username@$server_ip:~/"
fi
