#!/usr/bin/env bash
# script to perform A permanent 301 redirection
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo apt -y update
sudo apt -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-available/default
service nginx restart
