#!/usr/bin/env bash
# script to perform A permanent 301 redirection
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-available/default
service nginx restart
