#!/usr/bin/env bash
# script to install nginx on a server
sudo apt -y update
sudo apt -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
sed -i 's|location /\ {|location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n   }\n\n|' /etc/nginx/sites-available/default
sudo service nginx start
