#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
Hostname=$(hostname)
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;\n\terror_page 404 \/404.html;"
custom_header="include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By $Hostname;"

sudo apt -y update
sudo apt -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-available/default
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/$custom_header/" /etc/nginx/nginx.conf
sudo service nginx restart
