#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get install -y haproxy

sleep 5s

echo -e "\nfrontend http\n\tbind *:80\n\tdefault_backend http_back\n\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend http_back\n\tbalance roundrobin\n\tserver 395699-web-01 35.153.78.218:80 check\n\tserver 395699-web-02 18.207.112.26:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
